Rewrite zram-config
Signed-off-by: Ethan Dye <mrtops03@gmail.com>

diff --git a/zramsync b/zramsync
--- a/zramsync
+++ b/zramsync
@@ -1,27 +1,27 @@
-#!/bin/bash -x
+#!/usr/bin/env bash
 
+set -x
 
-LOG=/storage/zram/zramsync.log
+LOG="/storage/zram/zramsync.log"
+dir="$2"
+storeFile="${dir}/zram.tar"
 
-dir=$2
-storeFile=${dir}/zram.tar
+if [[ $# -ne 2 ]]; then echo "$(basename "$0"): wrong usage ! Arguments: sync|recover <dir>" | tee -a "$LOG"; exit 1; fi
 
-if [[ $# -ne 2 ]]; then echo "$(basename "$0"): wrong usage ! Arguments: sync|recover <dir>" | tee -a $LOG; exit 1; fi
+if ! [[ -f /etc/ztab ]]; then echo "FAILED (zram not installed)" | tee -a "$LOG"; exit 1; fi
 
-if [[ ! -f /etc/ztab ]]; then echo "FAILED (zram not installed)" | tee -a $LOG; exit 1; fi
-
-if [[ ! -d $dir ]]; then
+if ! [[ -d $dir ]]; then
 	mkdir -p "${dir}"
 fi
 
-if [[ "$1" = "recover" ]]; then
-	mode=recover
-	echo "zramsync recovery starting @ $(date)" | tee -a $LOG
-	inFile=/etc/ztab
+if [[ $1 == "recover" ]]; then
+	mode="recover"
+	echo "zramsync recovery starting @ $(date)" | tee -a "$LOG"
+	inFile="/etc/ztab"
 else
-	mode=sync
-	echo "zramsync creating backup @ $(date)" | tee -a $LOG
-	inFile=/usr/local/share/zram-config/zram-device-list
+	mode="sync"
+	echo "zramsync creating backup @ $(date)" | tee -a "$LOG"
+	inFile="${TMPDIR:-/tmp}/zram-device-list"
 	rm -f "$storeFile"
 fi
 
@@ -30,38 +30,37 @@ while read -r line; do
 		"#"*)
 			# Skip comment line
 			continue
-		;;
+			;;
+
 		"")
 			# Skip empty line
 			continue
 			;;
+
 		*)
 			set -- $line
-			if [[ "$1" = "dir" ]]; then
-				df -k | grep over | tee -a $LOG
+			if [[ $1 == "dir" ]] || [[ $1 == "log" ]]; then
+				df -k | grep over | tee -a "$LOG"
 
-				OLDWD=$(pwd)
+				OLDWD="$(pwd)"
 				if [[ "$mode" = "recover" ]]; then
-					cd /;
-					echo "tar --transform 's,^\.,'$5',' -rf ${storeFile} ." |tee -a $LOG
-					echo "recovering $5 ..." | tee -a $LOG
-					tar tvf "$storeFile" "$5" | tee -a $LOG
+					cd / || exit 1
+					echo "recovering ${5}..." | tee -a "$LOG"
+					echo "tar -xvf \"${storeFile}\" \"${5}\"" | tee -a "$LOG"
+					tar -xvf "$storeFile" "$5" | tee -a "$LOG"
 				else
-					ls -l $3/date
-					NEWDIR="/opt/zram${2}/upper"
-					#NEWDIR=$(df $5 | awk '/^over/ { print "/opt/zram/zram"substr($1, length($1))"/upper"}') # /opt/zram/zram$(f1 | tr -d 'a-z')/upper
-					echo "$NEWDIR" | tee -a $LOG
-					ls -ld /opt/zram /opt/zram/zram1 "$NEWDIR"
+					PARENTDIR="/opt/zram${2}"
+					NEWDIR="${PARENTDIR}/upper"
+					ls -ld /opt/zram "$PARENTDIR" "$NEWDIR" | tee -a "$LOG"
 					if [[ -d "$NEWDIR" ]]; then
-						cd $NEWDIR
-						echo "tar --transform 's,^\.,'$3',' -rf ${storeFile} ." | tee -a $LOG
-						echo "storing $3 ..." | tee -a $LOG
-						tar --transform 's,^\.,'$3',' -rf "${storeFile}" .
+						cd "$NEWDIR" || exit 1
+						echo "storing ${3}..." | tee -a "$LOG"
+						echo "tar --transform 's,^\.,'$3',' -rvf ${storeFile} ." | tee -a "$LOG"
+						tar --transform 's,^\.,'$3',' -rvf "${storeFile}" . | tee -a "$LOG"
 					fi
 				fi
 				cd $OLDWD
 			fi
 			;;
 	esac
-done < $inFile
-
+done < "$inFile"
